# Generated by Django 3.1 on 2020-12-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hipertension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=24)),
                ('apellido', models.CharField(max_length=24)),
                ('presion_s', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
