# Generated by Django 3.1 on 2020-12-14 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0003_hipertension_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hipertension',
            name='usuario',
        ),
    ]
