# Generated by Django 3.1 on 2020-12-15 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0006_auto_20201215_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hipertension',
            name='usuario',
        ),
        migrations.AddField(
            model_name='hipertension',
            name='Perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perfiles.perfil'),
        ),
    ]
