# Generated by Django 3.1 on 2020-12-15 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0008_auto_20201215_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hipertension',
            old_name='Perfil',
            new_name='usuarios',
        ),
    ]
