# Generated by Django 3.1 on 2020-12-15 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0009_auto_20201215_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hipertension',
            old_name='usuarios',
            new_name='usuario',
        ),
    ]
