# Generated by Django 3.1 on 2020-12-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0010_auto_20201215_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='hipertension',
            name='colesterol_t',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='hipertension',
            name='edad',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hipertension',
            name='genero',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='hipertension',
            name='imc',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='hipertension',
            name='presion_d',
            field=models.IntegerField(null=True),
        ),
    ]
